# Generated by Django 6.0 on 2026-01-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='invoice_type',
            new_name='invoice',
        ),
    ]
