# Generated by Django 6.0 on 2026-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_invoice_type_paiement_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='status',
            field=models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=10),
        ),
    ]
