# Generated by Django 6.0 on 2026-01-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_unite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active_current', 'Active current'), ('active_late', 'Active late'), ('expiring_soon_current', 'Expiring soon current')], default='active_current', max_length=30),
        ),
    ]
